"""Distributed key generation for the beacon — no trusted dealer (WHITEPAPER §7.4).

`rig/beacon.py` set up the threshold key with a trusted dealer who briefly knows
the whole group secret. A real deployment must never let any party hold it. This
implements Feldman-VSS DKG:

  1. each participant i deals a random degree-(t-1) polynomial f_i, publishes
     commitments C_i,j = g^{a_i,j} to its coefficients (Feldman VSS), and sends
     each participant m the share f_i(m);
  2. every recipient VERIFIES a received share against the dealer's commitments
     (g^{share} == Π C_i,j^{m^j}) and complains if it fails;
  3. the group secret is s = Σ_i f_i(0) — which no one computes — and each
     participant's share of it is s_m = Σ_i f_i(m); the group public key is
     Σ_i C_i,0.

The result is a t-of-n key identical in use to the dealt one (`rig/beacon.py`
partial_sign/combine/verify work unchanged), but produced with no single party
ever holding s. Commitments make every share verifiable, so a cheating dealer
is caught, not trusted.
"""

import hashlib
from dataclasses import dataclass

from py_ecc.optimized_bls12_381 import G1, add, curve_order, multiply, normalize

from .beacon import BeaconKeys


def _rand_scalar(seed: bytes) -> int:
    return int.from_bytes(hashlib.sha256(seed).digest(), "big") % curve_order


@dataclass
class Dealer:
    """One participant's secret polynomial + its public Feldman commitments."""
    idx: int
    coeffs: list                # secret: [a_0, a_1, ..., a_{t-1}]
    commitments: list           # public: [a_j · G1]

    @staticmethod
    def create(idx: int, t: int, seed: bytes) -> "Dealer":
        coeffs = [_rand_scalar(seed + bytes([idx, j])) for j in range(t)]
        commitments = [multiply(G1, a) for a in coeffs]
        return Dealer(idx, coeffs, commitments)

    def share_for(self, m: int) -> int:
        """f_i(m) — the share this dealer sends to participant m."""
        s = 0
        for j, a in enumerate(self.coeffs):
            s = (s + a * pow(m, j, curve_order)) % curve_order
        return s


def verify_share(share: int, m: int, commitments: list) -> bool:
    """Check g^share == Π C_j^{m^j}: the share lies on the committed polynomial."""
    lhs = multiply(G1, share)
    rhs = None
    for j, C in enumerate(commitments):
        term = multiply(C, pow(m, j, curve_order))
        rhs = term if rhs is None else add(rhs, term)
    return normalize(lhs) == normalize(rhs)


def run_dkg(n: int, t: int, seed: bytes = b"palimpsest-dkg") -> BeaconKeys:
    """Simulate the full DKG among n participants and return the group keys.

    Raises if any dealt share fails verification (a caught cheater)."""
    dealers = [Dealer.create(i, t, seed) for i in range(1, n + 1)]

    # every participant m verifies each dealer's share to it, then sums them
    shares = {}
    for m in range(1, n + 1):
        acc = 0
        for d in dealers:
            s = d.share_for(m)
            if not verify_share(s, m, d.commitments):
                raise ValueError(f"dealer {d.idx} sent participant {m} a bad share")
            acc = (acc + s) % curve_order
        shares[m] = acc                                  # s_m = Σ_i f_i(m)

    # group public key = Σ_i C_i,0 = (Σ_i a_i,0) · G1 = s · G1  (s never computed)
    group_pk = None
    for d in dealers:
        group_pk = d.commitments[0] if group_pk is None \
            else add(group_pk, d.commitments[0])

    partial_pks = {m: multiply(G1, shares[m]) for m in range(1, n + 1)}
    return BeaconKeys(group_pk=group_pk, shares=shares, partial_pks=partial_pks,
                      t=t, n=n)


if __name__ == "__main__":
    from py_ecc.bls.g2_primitives import G2_to_signature

    from .beacon import combine, partial_sign, randomness, verify
    print("=" * 68)
    print("  PALIMPSEST — DKG (no trusted dealer)")
    print("=" * 68)
    n, t = 5, 3
    keys = run_dkg(n, t)
    print(f"\n{t}-of-{n} group key generated by {n} participants; no party ever")
    print("held the group secret. Every dealt share was verified vs commitments.")

    # the DKG key works exactly like a dealt key for the beacon
    r = 99
    partials = {i: partial_sign(keys.shares[i], r) for i in (1, 2, 3)}
    g = combine(r, partials)
    ok = verify(g, r, keys.group_pk)
    # a different quorum agrees on the same value (still unbiasable)
    g2 = combine(r, {i: partial_sign(keys.shares[i], r) for i in (2, 4, 5)})
    same = G2_to_signature(g) == G2_to_signature(g2)
    print(f"\n  beacon round {r} verifies vs DKG group key: {ok}")
    print(f"  two quorums agree (unbiasable): {same}")
    print(f"  randomness: {randomness(g).hex()[:24]}")
    print("=" * 68)
    raise SystemExit(0 if ok and same else 1)
