"""Run all Phase 0 rig experiments and write results/report.md.

Usage: python3 -m rig.run_all
"""

import os

from .consensus_sim import run_consensus_suite
from .econ_sim import run_econ_suite
from .training_sim import run_all_training

OUT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       "results")


def fmt_money(x: float) -> str:
    return f"${x/1e6:.1f}M"


def main() -> None:
    lines = ["# Phase 0 rig — results", "",
             "Generated by `python3 -m rig.run_all` (seeded; reproducible). "
             "Toy models; the rig tests *mechanisms and economics*, not model "
             "quality (WHITEPAPER §11.3).", "",
             "## Headline findings", "",
             "1. **The chain is deterministic.** Every run replays bit-exact from "
             "genesis — the model-as-chain-state claim (§3.5/§6.3) holds under "
             "fixed-point aggregation.",
             "2. **Loss-scoring alone is not a poisoning defense, but the stack "
             "is.** Stealthy poison passes loss-scoring; robust aggregation "
             "dampens it, canary probes collapse it, and replay-excision erases "
             "it — three independent locks (§7.2), no single one sufficient.",
             "3. **Commit-reveal kills weight-copying.** Freeriding is "
             "negative-EV above a ~0.4% audit rate; honest evaluation is the only "
             "surviving validator strategy (§5.3).",
             "4. **51% is the right threshold for liveness, but state safety needs "
             "watchers.** Collusion turns unprofitable exactly at the majority "
             "boundary; without a challenge layer, a supermajority finalizes bad "
             "deltas ~83% of the time — the verification share (§9.2) is "
             "load-bearing, not optional.",
             "5. **The bootstrap tunnel closes — conditionally.** Base and "
             "aggressive demand cross over in 16–30 months under the emission "
             "cap; a $1.5M-ARR vertical never crosses. Vertical selection (§11.2) "
             "is the survival decision, quantified.", "",
             "Full tables and per-falsifier verdicts below.", ""]
    verdicts = []

    # ---- Training / chain experiments -------------------------------------
    t = run_all_training()
    a, b, c, d = t["A"], t["B"], t["C"], t["D_excised"]

    lines += [
        "## 1. Model-as-chain-state + poisoning (training_sim)", "",
        "Sybil coalition = 5 of 8 submitters; stealthy trigger in task-unused "
        "capacity (§12.3). Attack rate = fraction of triggered true-negatives "
        "flipped positive.", "",
        "| Run | Clean accuracy | Backdoor attack rate | Replay bit-exact |",
        "|---|---|---|---|",
        f"| A honest | {a.clean_acc:.3f} | {a.atk_rate:.3f} | {a.replay_ok} |",
        f"| B poison, loss-scoring only | {b.clean_acc:.3f} | {b.atk_rate:.3f} | {b.replay_ok} |",
        f"| C poison + canary probes | {c.clean_acc:.3f} | {c.atk_rate:.3f} | {c.replay_ok} |",
        f"| D = B after replay-excision | {d['clean_acc']:.3f} | {d['atk_rate']:.3f} | — |",
        "",
        "**Per-delta mechanism (the crisp test):** of the coalition's stealthy "
        f"poison deltas, **{b.poison_passed_loss}** passed loss-scoring (score > 0 "
        "— loss-scoring alone is blind, §7.2), and of those the canary probe "
        f"flagged **{c.poison_flagged_probe}** in run C "
        f"(rejected {c.rejected_by_probe} at inclusion).", "",
        "Note the emergent defense: even a 5/8 submitter majority only lifts the "
        f"attack rate to {b.atk_rate:.2f}, because robust aggregation (§3.4) trims "
        "minority-direction deltas — the honest majority dampens the backdoor "
        "before probes or excision act.", "",
    ]

    replay_ok = a.replay_ok and b.replay_ok and c.replay_ok
    backdoor_implants = b.atk_rate > a.atk_rate + 0.05   # poison run shows a backdoor
    loss_is_blind = b.poison_passed_loss > 20            # stealthy poison passes scoring
    probes_work = (c.poison_flagged_probe > 0            # probe mechanism fires, and
                   and c.atk_rate < 0.5 * b.atk_rate)    # end-state backdoor collapses
    excision_works = (d["atk_rate"] <= a.atk_rate + 0.02
                      and d["clean_acc"] > a.clean_acc - 0.03)

    verdicts += [
        ("Replay from genesis reconstructs bit-exact state (§3.5/§6.3)", replay_ok),
        ("Stealthy poison passes loss-scoring AND implants a chain-level backdoor "
         "— the §7.2 threat is real", loss_is_blind and backdoor_implants),
        ("Canary probes collapse the backdoor loss-scoring missed (falsifier #5, "
         "this attack class)", probes_work),
        ("Replay-excision drives the backdoor to baseline while preserving the "
         "model (§10.4)", excision_works),
    ]

    # ---- Consensus experiments --------------------------------------------
    k = run_consensus_suite()
    p = k["params"]
    lines += [
        "## 2. Scored-mempool attacks (consensus_sim)", "",
        f"Params: R={p['R']}, eval cost={p['c_eval']}R, slash={p['slash']}R, "
        f"self-dealing prize={p['miner_reward']}R, committee={p['committee']}.", "",
        "**Freeriders (weight-copiers / lazy validators) — EV per block vs honest:**", "",
        "| Audit rate | EV honest | EV freerider |",
        "|---|---|---|",
    ]
    for v in k["freeriders"]:
        lines.append(f"| {v.param:.0%} | {v.ev_honest:+.3f} | {v.ev_attacker:+.3f} |")
    lines += ["", f"Break-even audit rate (freeriding profitable below this): "
                  f"**{k['audit_breakeven']:.2%}**", "",
              "**Colluding coalition — EV per block and finalized-bad-delta rate "
              "(audit 5%, watcher coverage 95%):**", "",
              "| Global stake | EV honest | EV attack | Bad deltas finalized |",
              "|---|---|---|---|"]
    for v in k["colluders"]:
        lines.append(f"| {v.param:.0%} | {v.ev_honest:+.2f} | {v.ev_attacker:+.2f} "
                     f"| {v.state_safety_failures:.2%} |")
    lines += ["", "**State safety vs watcher coverage (coalition at 60% stake):**", "",
              "| Challenge coverage | Attacker EV | Bad deltas finalized |",
              "|---|---|---|"]
    for v in k["weak_watchers_at_60pct"]:
        lines.append(f"| {v.challenge_p:.0%} | {v.ev_attacker:+.2f} "
                     f"| {v.state_safety_failures:.2%} |")
    lines.append("")

    freerider_never_pays = all(v.ev_attacker < v.ev_honest
                               for v in k["freeriders"] if v.param >= 0.01)
    collusion_unprofitable_below_majority = all(
        v.ev_attacker <= v.ev_honest + 1e-9 for v in k["colluders"] if v.param < 0.5)
    majority_unprofitable_with_watchers = all(
        v.ev_attacker < 0 for v in k["colluders"] if v.param >= 0.5)
    safety_needs_watchers = any(v.state_safety_failures > 0.10
                                for v in k["weak_watchers_at_60pct"]
                                if v.challenge_p < 0.5)

    verdicts += [
        ("Freeriding loses money at ≥1% audit coverage (kills weight-copying, §5.3)",
         freerider_never_pays),
        ("Collusion below 51% global stake never beats honesty (falsifier #1)",
         collusion_unprofitable_below_majority),
        ("Even a >51% coalition has negative EV under 95% watcher coverage (§5.4/§5.5)",
         majority_unprofitable_with_watchers),
        ("BUT state safety degrades without watchers — challenge layer is "
         "load-bearing, fund it (§9.2 verification share)", safety_needs_watchers),
    ]

    # ---- Economics ---------------------------------------------------------
    e = run_econ_suite()
    lines += ["## 3. Bootstrap tunnel (econ_sim)", "",
              f"Training share {0.25:.0%}, steady burn $1.0M/yr, emission cap $20M, "
              "monotone sunset (§9.3).", "",
              "| Scenario | Bootstrap cost | Crossover month | Cumulative subsidy | "
              "Cap hit | Sunset steps |",
              "|---|---|---|---|---|---|"]
    for r in e:
        cross = str(r.crossover_month) if r.crossover_month is not None else "NEVER"
        lines.append(f"| {r.scenario} | {fmt_money(r.bootstrap_cost)} | {cross} "
                     f"| {fmt_money(r.cumulative_emission)} | {r.cap_hit} "
                     f"| {r.sunset_steps_taken} |")
    lines.append("")

    base_ok = all(r.crossover_month is not None and not r.cap_hit
                  for r in e if r.scenario in ("base", "aggressive"))
    conservative = [r for r in e if r.scenario == "conservative"]
    conservative_fails = all(r.crossover_month is None for r in conservative)

    verdicts += [
        ("Tunnel closes in base & aggressive demand without hitting the cap "
         "(falsifier #3)", base_ok),
        ("Conservative demand ($1.5M ARR cap) never crosses — confirms the §9.5 "
         "threshold: the vertical must clear ARR ≳ 4× steady burn / training "
         "share, or the network is an emissions machine", conservative_fails),
    ]

    # ---- Verdicts ----------------------------------------------------------
    lines += ["## Verdicts vs WHITEPAPER falsifiers (§12.6)", ""]
    for text, ok in verdicts:
        lines.append(f"- {'✅' if ok else '❌'} {text}")
    lines.append("")

    os.makedirs(OUT_DIR, exist_ok=True)
    path = os.path.join(OUT_DIR, "report.md")
    with open(path, "w") as f:
        f.write("\n".join(lines))

    print("\n".join(lines))
    print(f"\nWritten: {path}")
    if not all(ok for _, ok in verdicts):
        raise SystemExit(1)


if __name__ == "__main__":
    main()
