//! Palimpsest consensus core — the deterministic math every node must agree on.
//!
//! The Python rig (`rig/`) is the SPEC; this crate must reproduce it bit-exactly.
//! `node/vectors/golden.json` (generated by `scripts/golden_vectors.py`) is the
//! contract: `cargo test` fails unless every vector matches. The three classic
//! porting traps, handled explicitly:
//!
//!  * numpy `round` is round-half-to-EVEN  -> `f64::round_ties_even`, never `round`
//!  * numpy `floor_divide` floors           -> `i64::div_euclid`, never `/`
//!  * numpy `tobytes` is little-endian      -> `to_le_bytes` everywhere

use ed25519_dalek::{Signature, Signer, SigningKey, Verifier, VerifyingKey};
use sha2::{Digest, Sha256};

pub mod blocktree;
pub mod capacity;
pub mod da;
pub mod lottery;
pub mod token;

pub const SCALE: f64 = 65536.0; // 1 << 16 fixed-point scale

fn sha256_hex(bytes: &[u8]) -> String {
    hex::encode(Sha256::digest(bytes))
}

/// Public alias (module consumers need the genesis txset hash).
pub fn sha256_hex_pub(bytes: &[u8]) -> String {
    sha256_hex(bytes)
}

/// Unambiguous signing preimage: each field length-prefixed (4-byte BE) so no
/// field's contents can be confused with the structure. Byte-identical to the
/// Python reference `crypto.frame` — closes the '|'-delimiter injection hazard.
pub fn frame(parts: &[&[u8]]) -> Vec<u8> {
    let mut out = Vec::new();
    for p in parts {
        out.extend_from_slice(&(p.len() as u32).to_be_bytes());
        out.extend_from_slice(p);
    }
    out
}

/// Float delta -> int64 fixed-point. numpy's np.round rounds half to even.
pub fn quantize(delta: &[f64]) -> Vec<i64> {
    delta.iter().map(|x| (x * SCALE).round_ties_even() as i64).collect()
}

pub fn dequantize(q: &[i64]) -> Vec<f64> {
    q.iter().map(|&x| x as f64 / SCALE).collect()
}

/// Canonical little-endian byte serialization of an int64 weight vector
/// (numpy `.tobytes()` on our platforms).
pub fn int64_bytes(w: &[i64]) -> Vec<u8> {
    let mut out = Vec::with_capacity(w.len() * 8);
    for &x in w {
        out.extend_from_slice(&x.to_le_bytes());
    }
    out
}

/// sha256 over canonical weight bytes (§3.1).
pub fn state_root(w: &[i64]) -> String {
    sha256_hex(&int64_bytes(w))
}

/// sha256 of a delta body's canonical bytes.
pub fn delta_hash(body: &[u8]) -> String {
    sha256_hex(body)
}

/// Byzantine-robust aggregation (§3.4): per-coordinate sort, trim the top and
/// bottom `trim` fraction, integer mean with FLOOR division (matches
/// np.floor_divide, which floors; Rust `/` truncates — use div_euclid).
pub fn trimmed_mean(deltas: &[Vec<i64>], trim: f64) -> Vec<i64> {
    let k = deltas.len();
    assert!(k > 0);
    let n = deltas[0].len();
    let mut lo = (k as f64 * trim).floor() as usize;
    // Byzantine robustness at low miner counts: once k >= 3, always drop >= 1
    // from each end so a lone adversarial delta can't be averaged straight in
    // (matches rig/chain.py). k < 3 cannot be made robust.
    if k >= 3 {
        lo = lo.max(1);
    }
    let hi = k - lo;
    let (lo, hi) = if hi > lo { (lo, hi) } else { (0, k) };
    let m = (hi - lo) as i64;
    let mut out = vec![0i64; n];
    let mut col = vec![0i64; k];
    for i in 0..n {
        for (j, d) in deltas.iter().enumerate() {
            col[j] = d[i];
        }
        col.sort_unstable();
        // numpy sums with dtype=int64, which WRAPS on overflow (two's
        // complement). Mirror it with wrapping_add so a crafted block of
        // near-max deltas produces the identical result on every node instead
        // of panicking a debug build or diverging — the reference is the spec.
        let sum: i64 = col[lo..hi].iter().fold(0i64, |a, &b| a.wrapping_add(b));
        out[i] = sum.div_euclid(m);
    }
    out
}

/// Reconstruct a dense int64 delta from a compressed payload
/// (u32-LE indices + i32-LE values; everything else is zero).
pub fn decompress(n: usize, idx_bytes: &[u8], val_bytes: &[u8]) -> Vec<i64> {
    let mut out = vec![0i64; n];
    let k = idx_bytes.len() / 4;
    assert_eq!(val_bytes.len() / 4, k);
    for i in 0..k {
        let idx = u32::from_le_bytes(idx_bytes[i * 4..i * 4 + 4].try_into().unwrap()) as usize;
        let val = i32::from_le_bytes(val_bytes[i * 4..i * 4 + 4].try_into().unwrap()) as i64;
        out[idx] = val;
    }
    out
}

// ---------------------------------------------------------------------------
// Identity & transactions
// ---------------------------------------------------------------------------

pub struct Key {
    signing: SigningKey,
}

impl Key {
    /// Deterministic keypair from a 32-byte seed (same derivation as the
    /// Python reference: seed IS the Ed25519 secret).
    pub fn from_seed(seed: [u8; 32]) -> Self {
        Key { signing: SigningKey::from_bytes(&seed) }
    }

    pub fn pub_hex(&self) -> String {
        hex::encode(self.signing.verifying_key().to_bytes())
    }

    pub fn sign(&self, msg: &[u8]) -> Vec<u8> {
        self.signing.sign(msg).to_bytes().to_vec()
    }
}

pub fn verify_sig(pub_hex: &str, msg: &[u8], sig: &[u8]) -> bool {
    let Ok(pk_bytes) = hex::decode(pub_hex) else { return false };
    let Ok(pk_arr) = <[u8; 32]>::try_from(pk_bytes.as_slice()) else { return false };
    let Ok(vk) = VerifyingKey::from_bytes(&pk_arr) else { return false };
    let Ok(sig_arr) = <[u8; 64]>::try_from(sig) else { return false };
    vk.verify(msg, &Signature::from_bytes(&sig_arr)).is_ok()
}

/// A miner's signed delta commitment (§4.1).
#[derive(Clone, Debug)]
pub struct BackpropTx {
    pub miner: String,
    pub base_height: u64,
    pub shard_id: u64,
    pub delta_hash: String,
    pub da_pointer: String,
    pub bond: u64, // rev 4: stake bond the miner locks to submit (grains)
    // rev 5: PROVENANCE — content addresses of the data this gradient trained on.
    // Empty is rejected by block validation; the share pays these corpora's owners.
    pub data_refs: Vec<String>,
    pub sig: Vec<u8>,
}

impl BackpropTx {
    /// Sorted, de-duplicated provenance set — the canonical data_refs.
    pub fn canonical_refs(&self) -> Vec<String> {
        let mut r = self.data_refs.clone();
        r.sort();
        r.dedup();
        r
    }

    /// Must match the Python reference byte-for-byte (length-prefixed framing).
    pub fn signing_bytes(&self) -> Vec<u8> {
        let refs = self.canonical_refs();
        let base = self.base_height.to_string();
        let shard = self.shard_id.to_string();
        let bond = self.bond.to_string();
        let count = refs.len().to_string();
        let mut parts: Vec<&[u8]> = vec![
            b"backprop",
            self.miner.as_bytes(),
            base.as_bytes(),
            shard.as_bytes(),
            self.delta_hash.as_bytes(),
            self.da_pointer.as_bytes(),
            bond.as_bytes(),
            count.as_bytes(),
        ];
        for r in &refs {
            parts.push(r.as_bytes());
        }
        frame(&parts)
    }

    pub fn txid(&self) -> String {
        sha256_hex(&self.signing_bytes())
    }

    pub fn verify(&self) -> bool {
        verify_sig(&self.miner, &self.signing_bytes(), &self.sig)
    }
}

/// Root over a transaction set: sorted txids joined with '|', hashed.
pub fn txset_root(txids: &[String]) -> String {
    let mut sorted: Vec<&String> = txids.iter().collect();
    sorted.sort();
    let joined = sorted.iter().map(|s| s.as_str()).collect::<Vec<_>>().join("|");
    sha256_hex(joined.as_bytes())
}

// ---------------------------------------------------------------------------
// Block header
// ---------------------------------------------------------------------------

#[derive(Clone, Debug)]
pub struct Header {
    pub height: u64,
    pub prev_hash: String,
    pub state_root: String,
    pub txset_root: String,
    pub n_txs: u64,
    pub work: u64,
    pub proposer: String,
    pub transfer_root: String, // rev 2: commitment to the transfer set
    pub ledger_root: String,   // rev 2: token ledger AFTER this block
    pub data_root: String,     // rev 3: commitment to the data-lane tx set
    pub vrf_proof: String,     // rev 4: proposer's VRF proof (hex); work derives from it
    pub score_root: String,    // rev 7: commitment to the proposer's delta scores
}

impl Header {
    /// The canonical serialization is Python's `json.dumps(dict, sort_keys=True)`
    /// with default separators (", " and ": "), keys in lexicographic order:
    /// data_root, height, ledger_root, n_txs, prev_hash, proposer, score_root,
    /// state_root, transfer_root, txset_root, vrf_proof, work. Values are hex
    /// strings and ints, so no JSON string escaping arises.
    pub fn canonical_json(&self) -> String {
        format!(
            "{{\"data_root\": \"{}\", \"height\": {}, \"ledger_root\": \"{}\", \"n_txs\": {}, \"prev_hash\": \"{}\", \"proposer\": \"{}\", \"score_root\": \"{}\", \"state_root\": \"{}\", \"transfer_root\": \"{}\", \"txset_root\": \"{}\", \"vrf_proof\": \"{}\", \"work\": {}}}",
            self.data_root, self.height, self.ledger_root, self.n_txs,
            self.prev_hash, self.proposer, self.score_root, self.state_root,
            self.transfer_root, self.txset_root, self.vrf_proof, self.work
        )
    }

    pub fn block_hash(&self) -> String {
        sha256_hex(self.canonical_json().as_bytes())
    }
}
