//! The contract: every vector generated by the Python reference
//! (scripts/golden_vectors.py -> node/vectors/golden.json) must reproduce
//! bit-exactly. If this fails, the Rust node is wrong — the rig is the spec.

use palimpsest_core as core;
use serde_json::Value;

fn vectors() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../vectors/golden.json");
    serde_json::from_str(&std::fs::read_to_string(path).expect("golden.json missing"))
        .expect("golden.json invalid")
}

fn f64s(v: &Value) -> Vec<f64> {
    v.as_array().unwrap().iter().map(|x| x.as_f64().unwrap()).collect()
}
fn i64s(v: &Value) -> Vec<i64> {
    v.as_array().unwrap().iter().map(|x| x.as_i64().unwrap()).collect()
}

#[test]
fn quantize_matches_reference() {
    for case in vectors()["quantize"].as_array().unwrap() {
        assert_eq!(core::quantize(&f64s(&case["f"])), i64s(&case["q"]),
                   "quantize mismatch (round-half-to-even?)");
    }
}

#[test]
fn state_root_matches_reference() {
    for case in vectors()["state_root"].as_array().unwrap() {
        assert_eq!(core::state_root(&i64s(&case["w"])),
                   case["root"].as_str().unwrap(),
                   "state_root mismatch (endianness?)");
    }
}

#[test]
fn trimmed_mean_matches_reference() {
    for case in vectors()["trimmed_mean"].as_array().unwrap() {
        let deltas: Vec<Vec<i64>> = case["deltas"].as_array().unwrap()
            .iter().map(i64s).collect();
        assert_eq!(core::trimmed_mean(&deltas, 0.2), i64s(&case["mean"]),
                   "trimmed_mean mismatch (floor division?)");
    }
}

#[test]
fn delta_hash_matches_reference() {
    for case in vectors()["delta_hash"].as_array().unwrap() {
        let d = i64s(&case["delta"]);
        assert_eq!(core::delta_hash(&core::int64_bytes(&d)),
                   case["hash"].as_str().unwrap());
    }
}

#[test]
fn decompress_matches_reference() {
    for case in vectors()["decompress"].as_array().unwrap() {
        let idx = hex::decode(case["idx_hex"].as_str().unwrap()).unwrap();
        let val = hex::decode(case["val_hex"].as_str().unwrap()).unwrap();
        let n = case["n"].as_u64().unwrap() as usize;
        assert_eq!(core::decompress(n, &idx, &val), i64s(&case["dense"]));
    }
}

#[test]
fn ed25519_matches_reference() {
    for case in vectors()["ed25519"].as_array().unwrap() {
        let seed: [u8; 32] = hex::decode(case["seed_hex"].as_str().unwrap())
            .unwrap().try_into().unwrap();
        let key = core::Key::from_seed(seed);
        assert_eq!(key.pub_hex(), case["pub_hex"].as_str().unwrap(),
                   "pubkey derivation mismatch");
        let msg = hex::decode(case["msg_hex"].as_str().unwrap()).unwrap();
        assert_eq!(hex::encode(key.sign(&msg)), case["sig_hex"].as_str().unwrap(),
                   "signature mismatch (RFC 8032 is deterministic)");
        assert!(core::verify_sig(&key.pub_hex(), &msg,
                                 &hex::decode(case["sig_hex"].as_str().unwrap()).unwrap()));
    }
}

#[test]
fn backprop_tx_matches_reference() {
    for case in vectors()["backprop_tx"].as_array().unwrap() {
        let tx = core::BackpropTx {
            miner: case["miner"].as_str().unwrap().into(),
            base_height: case["base_height"].as_u64().unwrap(),
            shard_id: case["shard_id"].as_u64().unwrap(),
            delta_hash: case["delta_hash"].as_str().unwrap().into(),
            da_pointer: case["da_pointer"].as_str().unwrap().into(),
            sig: hex::decode(case["sig_hex"].as_str().unwrap()).unwrap(),
        };
        assert_eq!(hex::encode(tx.signing_bytes()),
                   case["signing_bytes_hex"].as_str().unwrap());
        assert_eq!(tx.txid(), case["txid"].as_str().unwrap());
        assert!(tx.verify(), "tx signature must verify");
    }
}

#[test]
fn txset_root_matches_reference() {
    for case in vectors()["txset_root"].as_array().unwrap() {
        let ids: Vec<String> = case["txids"].as_array().unwrap()
            .iter().map(|x| x.as_str().unwrap().to_string()).collect();
        assert_eq!(core::txset_root(&ids), case["root"].as_str().unwrap());
    }
}

#[test]
fn header_hash_matches_reference() {
    for case in vectors()["header"].as_array().unwrap() {
        let h = core::Header {
            height: case["height"].as_u64().unwrap(),
            prev_hash: case["prev_hash"].as_str().unwrap().into(),
            state_root: case["state_root"].as_str().unwrap().into(),
            txset_root: case["txset_root"].as_str().unwrap().into(),
            n_txs: case["n_txs"].as_u64().unwrap(),
            work: case["work"].as_u64().unwrap(),
            proposer: case["proposer"].as_str().unwrap().into(),
        };
        assert_eq!(h.canonical_json(), case["canonical_json"].as_str().unwrap(),
                   "canonical JSON must match python json.dumps(sort_keys=True)");
        assert_eq!(h.block_hash(), case["hash"].as_str().unwrap());
    }
}
